openmrs/openmrs-esm-cohortbuilder-app

src/cohort-builder.resource.ts
src/cohort-builder.tsx
src/cohort-builder.utils.ts
src/components/search-by-concepts/search-by-concepts.component.tsx
src/components/search-by-concepts/search-by-concepts.test.tsx
src/components/search-by-concepts/search-concept/search-concept.component.tsx
src/components/search-by-concepts/search-concept/search-concept.resource.ts
src/components/search-by-concepts/search-concept/search-concept.test.tsx
src/components/search-by-demographics/search-by-demographics.component.tsx
src/components/search-by-demographics/search-by-demographics.style.scss
src/components/search-by-demographics/search-by-demographics.test.tsx
src/components/search-by-demographics/search-by-demographics.utils.ts
src/components/search-by-person-attributes/search-by-person-attributes.component.tsx
src/components/search-by-person-attributes/search-by-person-attributes.resource.ts
src/components/search-by-person-attributes/search-by-person-attributes.style.scss
src/components/search-by-person-attributes/search-by-person-attributes.test.tsx
src/components/search-by-person-attributes/search-by-person-attributes.utils.ts
src/components/search-history/search-history-options/search-history-options.component.tsx
src/components/search-history/search-history-options/search-history-options.resources.ts
src/components/search-history/search-history-options/search-history-options.test.tsx
src/components/search-history/search-history.component.tsx
src/components/search-history/search-history.test.tsx
src/components/search-history/search-history.utils.ts
src/components/search-results-table/search-results-table.component.tsx
src/components/search-results-table/search-results-table.test.tsx
src/types/index.ts
translations/en.json

- The purpose of this PR is to fix #[O3-1303](https://issues.openmrs.org/browse/O3-1303)
- To give the user the ability to search for patients based on demographics and personal attributes
- Created the search by demographics and search by person attributes components
- Added styles to match the design
- Wrote tests
- Updated the translations

O3-1303: Implement the search by demographics and person attributes feature

---

.eslintrc
jest.config.json
src/cohort-builder.resource.ts
src/cohort-builder.tsx
src/components/search-by-concepts/search-by-concepts.component.tsx
src/components/search-by-concepts/search-by-concepts.test.tsx
src/components/search-by-demographics/search-by-demographics.component.tsx
src/components/search-by-demographics/search-by-demographics.test.tsx
src/components/search-by-encounters/search-by-encounters.component.tsx
src/components/search-by-encounters/search-by-encounters.resources.ts
src/components/search-by-encounters/search-by-encounters.style.scss
src/components/search-by-encounters/search-by-encounters.test.tsx
src/components/search-by-encounters/search-by-encounters.utils.ts
src/components/search-by-location/search-by-location.component.tsx
src/components/search-by-location/search-by-location.style.scss
src/components/search-by-location/search-by-location.test.tsx
src/components/search-by-location/search-by-location.utils.ts
src/components/search-by-person-attributes/search-by-person-attributes.component.tsx
src/components/search-by-person-attributes/search-by-person-attributes.resource.ts
src/components/search-by-person-attributes/search-by-person-attributes.test.tsx
src/components/search-history/search-history-options/search-history-options.component.tsx
src/types/index.ts
translations/en.json

- The purpose of this PR is to fix #[O3-1304](https://issues.openmrs.org/browse/O3-1304)
- To give the user the ability to search for patients based on encounters and location
- Created the search by encounters and search by location
- Added styles to match the design
- Wrote tests
- Updated the translations

O3-1304: Implement the search by encounters and search by location feature

---

package.json
src/cohort-builder.resource.ts
src/components/search-by-concepts/search-by-concepts.component.tsx
src/components/search-by-demographics/search-by-demographics.component.tsx
src/components/search-by-encounters/search-by-encounters.component.tsx
src/components/search-by-encounters/search-by-encounters.resources.ts
src/components/search-by-encounters/search-by-encounters.test.tsx
src/components/search-by-location/search-by-location.component.tsx
src/components/search-by-location/search-by-location.test.tsx
src/components/search-by-person-attributes/search-by-person-attributes.component.tsx
src/components/search-by-person-attributes/search-by-person-attributes.resource.ts
src/components/search-by-person-attributes/search-by-person-attributes.test.tsx
yarn.lock

- The purpose of this PR is to fix #[O3-1417](https://issues.openmrs.org/browse/O3-1417)
- To improve the data fetching performance
- Installed SWR
- Created hooks for the APIs

O3-1417: Use SWR for data fetching

---

.github/workflows/node.js.yml

- The purpose of this PR is to fix #[O3-1427](https://issues.openmrs.org/browse/O3-1427)
- To deploy the app to the dev server
- Updated the `node.js.yml` with the new deploy job

O3-1427: Add the deploy job to the workflow

---

src/cohort-builder.scss
src/cohort-builder.tsx
src/components/search-by-concepts/search-by-concepts.component.tsx
src/components/search-by-concepts/search-by-concepts.style.scss
src/components/search-by-demographics/search-by-demographics.component.tsx
src/components/search-by-demographics/search-by-demographics.style.scss

- The purpose of this PR is to fix #[O3-1443](https://issues.openmrs.org/browse/O3-1443)
- Improve the tablet and small desktop layout
- Updated the styles

O3-1443: Improve the tablet and small desktop layout

---

src/components/saved-cohorts/saved-cohorts.component.tsx
src/components/saved-queries/saved-queries.component.tsx

- The purpose of this PR is to fix #[O3-1446](https://issues.openmrs.org/browse/O3-1446)
- Avoid sending infinite calls
- Updated the useEffect 
- Removed the Id field from the table

O3-1446: Fix the infinite API calls issue

---

src/cohort-builder.scss
src/cohort-builder.tsx
src/components/composition/composition.component.tsx
src/components/composition/composition.style.css
src/components/search-by-encounters/search-by-encounters.component.tsx

- The purpose of this PR is to fix #[O3-1471](https://issues.openmrs.org/browse/O3-1471)
- To fix the broken UIs
- Added styles to match the original design

O3-1471: Add css to fix the broken UI layout

---

src/cohort-builder.scss
src/cohort-builder.tsx
src/components/saved-cohorts/saved-cohorts.scss
src/components/saved-queries/saved-queries.scss

- The purpose of this PR is to fix #[O3-1482](https://issues.openmrs.org/browse/O3-1482)
- Avoid overriding CSS in other ESM modules
- Wrapped the global selectors with a custom class

O3-1482: Wrap the global selectors with a custom class

---

src/cohort-builder.tsx

- The purpose of this PR is to fix #[O3-1513](https://issues.openmrs.org/browse/O3-1513)
- To show only the things that implemented
- Removed the SQL tab from the code

O3-1513: Remove SQL tab from the side navbar

---

src/components/composition/composition.test.tsx
src/components/composition/composition.utils.ts
src/components/search-by-demographics/search-by-demographics.test.tsx
src/components/search-by-drug-orders/search-by-drug-orders.test.tsx
src/components/search-by-enrollments/search-by-enrollments.test.tsx
src/components/search-by-location/search-by-location.test.tsx
src/types/index.ts

- The purpose of this PR is to fix #[O3-1531](https://issues.openmrs.org/browse/O3-1531)
- To fix the composition feature
- Uncommented the commented code snippets
- Fix the E2E test

O3-1531: Fix the create composition query function

---

.github/workflows/node.js.yml

- The purpose of this PR is to fix #[O3-1543](https://issues.openmrs.org/browse/O3-1543)
- To update the workflow to publish the app on npm
- Updated the pre-release job

O3-1543: Update the pre_release job in the GitHub workflow

---

.github/workflows/node.js.yml

- The purpose of this PR is to fix #[O3-1545](https://issues.openmrs.org/browse/O3-1545)
- To update the workflow to deploy the app on the refapp
- Updated the deploy job

O3-1545: Update the deploy job in the workflow

---

.github/workflows/node.js.yml
package.json

Potentially fixes an issue where this app doesn't get published correctly.

(chore) Fix app publishing

---

.github/workflows/node.js.yml

Fixes the CI's version command which I inadvertently broke after modifying it to use a version compatible with Yarn 3 (whereas this project is still on Yarn v1).

(chore) Fix version command

---

.github/workflows/e2e.yml
.gitignore
e2e/README.md
e2e/core/global-setup.ts
e2e/core/index.ts
e2e/core/test.ts
e2e/fixtures/api.ts
e2e/fixtures/index.ts
e2e/pages/cohort-builder-page.ts
e2e/pages/index.ts
e2e/specs/example.spec.ts
e2e/support/docker-compose.yml
example.env
jest.config.js
package.json
playwright.config.ts
yarn.lock

- In this pull request E2E end tests were configured using playwright. All the necessary documents are created. The test configurations are similar to the form builder configuration.
*None.*
https://issues.openmrs.org/browse/O3-2069
*None.*

(test) O3-2269: Configure E2E tests with playwright

---

e2e/pages/cohort-builder-page.ts
e2e/specs/demographics.spec.ts
e2e/specs/example.spec.ts
playwright.config.ts

- In this test, search by demographics feature is being tested, A simple demographics search query is being made and check for the success notification.
https://issues.openmrs.org/browse/O3-2271
None

(test) O3-2271: Write the search by demographics E2E test

---

e2e/pages/cohort-builder-page.ts
e2e/specs/location.spec.ts

- In this test, search by location feature is being tested, A simple demographics search query is being made and check for the success notification.
https://issues.openmrs.org/browse/O3-2273
None

(test) O3-2273: Write a E2E test for search by location feature

---

.github/workflows/e2e.yml
e2e/pages/cohort-builder-page.ts
e2e/specs/enrollements.spec.ts
e2e/specs/location.spec.ts

- In this test, search by enrollments feature is being tested, A simple enrollments search query is being made and check for the success notification.
https://issues.openmrs.org/browse/O3-2274
None

(test) O3-2274: Write a E2E test for search by enrollments feature

---

e2e/pages/cohort-builder-page.ts
e2e/specs/concepts.spec.ts

- In this test, search by concepts feature is being tested, A simple concepts search query is being made and check for the success notification.
https://issues.openmrs.org/browse/O3-2270
None

(test) O3-2270: Write a E2E test for search by concepts feature

---

e2e/pages/cohort-builder-page.ts
e2e/specs/person-attributes.spec.ts

- In this test, search by person attributes feature is being tested, A simple person attributes search query is being made and check for the success notification.
https://issues.openmrs.org/browse/O3-2319
None

(test) O3-2319: Write a E2E test for search by person attributes feature

---

e2e/pages/cohort-builder-page.ts
e2e/specs/encounters.spec.ts

- In this test, search by person attributes encounters is being tested, A simple encounters search query is being made and check for the success notification.
https://issues.openmrs.org/browse/O3-2272
None

(test): O3-2272: Write an E2E test for search by encounters

---

e2e/pages/cohort-builder-page.ts
e2e/specs/composition.spec.ts

- In this test, search by search compositions is being tested, A simple search composition is being made and checked for the success notification.
https://issues.openmrs.org/browse/O3-2276
None

(test) O3-2276: Write an E2E test for search composition

---

.gitignore
e2e/support/bamboo/docker-compose.yml
e2e/support/bamboo/e2e-test-runner.sh
e2e/support/bamboo/playwright.Dockerfile
package.json
playwright.config.ts
yarn.lock

The purpose of this PR is to add relevant docker files to run E2E tests for the patient chart in bamboo.
This setup has been already tested at: https://ci.openmrs.org/browse/REFAPP-D3E-RCBET-330/test
https://issues.openmrs.org/browse/O3-2516

(chore) O3-2516: Add docker setup to run E2E on Bamboo

---

package.json

This PR cuts a new major release of this project.

(chore) Release 4.0.0

---

package.json
yarn.lock

The purpose of this PR is to bump playwright version from 1.44.0 to 1.49.0

(chore) Bump playwright version

---

yarn.lock

This PR bumps openmrs core and framework.

(chore): Bump Openmrs core and framework

---

package.json

This PR cuts a patch release. The draft changelog:
* (chore) Bump playwright version by @jayasanka-sack in https://github.com/openmrs/openmrs-esm-cohortbuilder-app/pull/97
* (chore) Update CI workflow by @denniskigen in https://github.com/openmrs/openmrs-esm-cohortbuilder-app/pull/98

(chore): Release v4.0.2

---

package.json
src/components/search-by-concepts/search-by-concepts.test.tsx

Cuts a patch release of Cohort Builder consisting of backwards-compatible bug fixes:
* (chore) Bump http-proxy-middleware from 2.0.7 to 2.0.9 by @dependabot in https://github.com/openmrs/openmrs-esm-cohortbuilder-app/pull/105
* (chore) Bump @carbon/react to v1.76.0 by @denniskigen in https://github.com/openmrs/openmrs-esm-cohortbuilder-app/pull/104
* (chore) Add automated dependency update workflow by @denniskigen in https://github.com/openmrs/openmrs-esm-cohortbuilder-app/pull/103

(chore) Release v4.0.3

---

README.md

Update README.md to point to O3 Docs.
Update README.md to point to O3 docs.

(docs) Update links to O3 developer documentation in README

---

package.json

This PR is to release a patch release of this repository.
This release includes following changes:
* (chore) O3-4745: Fix failing dependency auto-update CI workflow by @denniskigen in #141

(chore) Release v4.0.4
